import { ApolloClient, gql, InMemoryCache } from '@apollo/client'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://rickandmortyapi.com/graphql',
    cache: new InMemoryCache(),
  })

  const { data } = await client.query({
    query: gql`
      query {
        characters(page: 1) {
          info {
            count
            pages
            next
            prev
          }
          results {
            id
            name
            image
          }
        }
      }
    `
  });

  const characters = data.characters.results;
  const info = data.characters.info;

  return {
    props: {
      characters,
      info
    },
  }
}

interface Props {
  characters: any
  info: any
}

const Home = ({ characters, info }: Props) => {
  console.log(characters)
  console.log(info);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <hr />

      <ul>
        <li>{info.count} characters</li>
        <li>{info.pages} pages</li>
      </ul>
      <button disabled={info.prev === null} onClick={() => console.log('previous')}>Previous</button>
      <button disabled={info.next === null} onClick={() => console.log('next')}>Next</button>

      <hr />

      {
        characters.map((character: any) => (
          <div key={character.id}>
            <img src={character.image} />
            <h2>{character.name}</h2>
          </div>
        ))
      }
    </div>
  )
}

export default Home
